# Generated by Django 5.2.7 on 2025-10-30 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0003_refreshlog_alter_country_estimated_gdp_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RefreshLog',
        ),
    ]
